### ISSUE TITLE
Jetpack Compose

### ISSUE THREAD

**Issue by btentimishov** [muratozturk5/Mova#1]
Did you think to add Jetpack Compose to the project? 

What do you think about it?

**Comment by muratozturk5** [comment]
> Did you think to add Jetpack Compose to the project? 
> 
> 
> 
> What do you think about it? 

I have planed to make Jetpack Compose and SwiftUI versions, stay tuned.

**Comment by btentimishov** [comment]
> > Did you think to add Jetpack Compose to the project?
> > What do you think about it?
> 
> I have planed to make Jetpack Compose and SwiftUI versions, stay tuned.

Cool, I would like to see it!
